### ISSUE TITLE
При регистрации Фамилия и имя не сохраняется в БД

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#115]
### **How To Do?**

Нужно поправить хендлер регистрации, и сервисы/репозитории.
Заодно нужно отрефачить: 
- `servcies/user.py` - находится в core, хотя используется только на стороне бота. Переместить файл в `bot/services/`
- Переместить в конструктор переменные:
  ```python
  # Сейчас:
  user = User()
  user.telegram_id = telegram_id
  user.username = username

  # Должно быть:
  user = User(telegram_id=telegram_id, username=username)
  # Также эту часть кода лучше перенести в репозиторий. 
  ```

### **Where?**
`src/core/db/repository/user.py`
`src/core/services/user.py`
`src/bot/handlers/registration.py`

**Comment by ArtemBalandin81** [comment]
PR:
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/117
