### ISSUE TITLE
Добавить кнопку "подробнее" к задаче.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#138]
# How To Do?

После нажатия кнопки, сообщение об задаче становится более подробным. "Подробности" можно взять из `Task.description`

# Where?

`src/bot/handlers/tasks.py`

**Comment by KonstKorn** [comment]
@MikeScotte @NiKuma0  Я доделывал предыдущую задачу, к этой еще не приступил. У меня отключили пачку. Если это не проблема, то я готов сегодня начать делать эту задачу и общаться тут.

**Comment by MikeScotte** [comment]
Хорошо

**Comment by MikeScotte** [comment]
@KonstKorn  сегодня тебя должны восстановить в пачке

**Comment by KonstKorn** [comment]
@MikeScotte было бы хорошо, как раз по этой задаче хотел сегодня ПР выложить)

**Comment by MikeScotte** [comment]
@KonstKorn мне ответили, что завтра тебя подключат

**Comment by KonstKorn** [comment]
@MikeScotte хорошо. Спасибо!
@NiKuma0 @MikeScotte создал ПР - https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/145#partial-pull-merging
как подключат пачку туда продублирую

**Comment by MikeScotte** [comment]
@KonstKorn можешь в Связанные запросы на вытягивание добавить ветку. Посмотри у других
 тасок как сделано

**Comment by MikeScotte** [comment]
@KonstKorn можешь в Связанные запросы на вытягивание добавить ветку. Посмотри у других
 тасок как сделано

**Comment by KonstKorn** [comment]
ПР обновил в соответствии с ревью

**Comment by MikeScotte** [comment]
@KonstKorn  Привет, напиши, пожалуйста, свою почту, чтобы тебя восстановили в пачке

**Comment by KonstKorn** [comment]
@MikeScotte Привет! kkorneev@yandex.ru
