### ISSUE TITLE
Добавить роут со статистикой.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#149]
# Why?

Статистику будет получать наш фронт (админка). 

# How To Do?

Нужно опираться на схему API из старого проекта. 
Пока опишим схему `Stastic` и простой хендлер который будет возвращать эту схему, пока только с кол-во пользователей (все остальные поля будут пустыми).

# Where?

`src/api/routers`

**Comment by igor-sidorov** [comment]
Откуда брать количество пользователей? Количество каких пользователей возвращать?

**Comment by igor-sidorov** [comment]
https://github.com/ProCharity/ProCharity_bot/blob/develop/app/front/analytics.py#L22
