### ISSUE TITLE
Сохранения категорий не в контекст а сразу в БД.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#161]
# Why?

Сейчас категории обновляются у пользователя только когда он нажимает на кнопку "Готово", можно лучше - сразу сохранять в БД. 

# How To Do?

Убрать использование `context` для сохранения/выгрузки выбранных категорий, вместо этого использовать `UserRepository`. 

# Where?

`src/bot/handlers/categories.py`

**Comment by VadimVolkovsky** [comment]
т.е при каждом нажатии на категорию сразу же сохранять/удалять ее в БД ?


![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/b2499472-1d51-44a7-8677-47db5af6455e)
