### ISSUE TITLE
Добавить запуск в тестовом режиме github actions.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#163]
# Why?

Cейчас любой ПР попадает на сервер, где его легко будет тестировать, и где он может все поломать. Т.к. скоро подтянутся тестировщики, будет неудобно если вдруг приложение упадёт из-за очередного ПР-а.

# How To Do?

В теге `on: ...` убрать `pull_request: ...` оставить только `push: ...`  (при пуше в ветку) и `workflow_dispatch:` чтобы можно было запускать в ручную. 

# Where?

`.github/workflows/deploy_stage.yaml`

**Comment by KonstKorn** [comment]
@NiKuma0 Привет! Мне только удалить пару строк или еще дописать что-то надо (к примеру, тесты чтобы перед/вместе с deploy запускались)? 
П.С. Я посмотрел test.py в проекте и исправил импорт с pydantic на pydantic_settings, так как BaseSettings не импортировались.
