### ISSUE TITLE
Добавить login для админа.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#189]
# Why?

Админы должны получить доступ к адмнике. 

# How To Do?

Напишем простой хендлер, [как в старом боте](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/auth/login.py#L21), принимающий логин и пароль. Возвращать будет `token` и `refresh token`. Нужно чтобы старая API совпадала с новой на 100%, изменить только реализацию.

Уже был сделан код с генерации токена, но лучше от него отказаться и использовать [FastAPI JWT Auth](https://github.com/IndominusByte/fastapi-jwt-auth/). Старую версию нужно почистить (`src/api/services/admin_service.py`).

# Where?

`src/api/endpoints/admin_login.py`

**Comment by akiqq** [comment]
@NiKuma0 привет, есть проблемы с [FastAPI JWT Auth](https://github.com/IndominusByte/fastapi-jwt-auth/)
fastapi_jwt_auth не поддерживает 2 версию pydantic
https://github.com/IndominusByte/fastapi-jwt-auth/issues/98
вот такая ошибка падает, как можно увидеть решается это исключительно даунгрейдом pydantic до 1 версии
нашел такую библиотечку: https://github.com/k4black/fastapi-jwt все необходимое в ней имеется из коробки, но ей чуть больше года всего
собственно какой библиотекой реализовывать в таком случае, или есть фичи какие-то?
