### ISSUE TITLE
Возможность уведомить одним запросом группу пользователей.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#190]
# Why? 
Запрос от разработчика сайта procharity: "Нам по боту нужно еще сделать такой кейс - когда мы отправляем не одно сообщение, а сразу массив данных. Дело в том, что у нас есть рассылки, где письма отправляются сразу группе пользователей и хотелось бы сделать один запрос по всем сразу. В каждом элементе группы будем отправлять user_id (чтобы потом смогли распределить нужным) и собственно само сообщение"

# How To Do? 
Будет ждать такой json на `api/messages/group`:
```json
{
  "messages": [
    {"telegram_id": 1123, "message": "some text"},
    {"telegram_id": 7984, "message": "some text"},
    {"telegram_id": 1156, "message": "some text"},
    {"telegram_id": 1134, "message": "some text"}
  ]
}
```
Отправить всем уведомления, и вернуть число успешных отправленных сообщений и не успешных.

# Where? 
`src/api/endpoints/notification.py`

**Comment by PavelPrist** [comment]
отправил на ревью, проверяйте пожалуйста
