### ISSUE TITLE
Дать доступ к БД тестировщикам.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#201]
Нужно открыть порты (в docker compose), и создать пользователя в БД (для этого нужно зайти на сервер). Всю инфу (логин, пароль) скинуть мне в личку.

**Comment by Sovraska** [comment]
@NiKuma0 Привет   Я посидел   подумал


вот как я понял задачу:


Создать пользователя в БД и скинуть тебе доступ
его нужно создать на сервере
при этом пробросив порты в контейнер с базой

Но есть несколько вопросов
1.  о каком сервере идёт речь ? Какой-то тестовый или прод (непонятно). Нашёл в документации только этот dev@158.160.40.190, но на нём что-то непонятное )

2. как будут тестировщики взаимодействовать с БД ?
Просто создать юзера на сервере и дать доступ ?
Что бы они после через терминал, что то для себя вытаскивали
или создать какой-то скрипт для выдачи им данных.


Я мало погружён в тему, а потому сложно налету схватить твою мысль

**Comment by NiKuma0** [comment]
@Sovraska Все верно понял. 1) О тестовом, другого нет. В папке `/home/deployment-user` есть файл с docker-compose и запущенные контейнеры. Нужно зайти в контейнер с БД и там создать пользователя. 2) Есть множество клиентов для коннекта к БД, достаточно открыть порты и дать логин пароль.

**Comment by Sovraska** [comment]
@NiKuma0  В лс закинул логин пароль и настройки подклюючения через PgAdmin4

**Comment by Sovraska** [comment]
докер композ изменил на сервере, а в репе пока не трогал.
 там тоже изменить ?

**Comment by NiKuma0** [comment]
> докер композ изменил на сервере, а в репе пока не трогал. там тоже изменить ?

Только в репе и нужно было изменить.

**Comment by Sovraska** [comment]
ахах понял
