### ISSUE TITLE
Добавить `healthcheck` запуск в workflow

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#285]
# How To Do?

[Подобный воркфлоу есть в ломая барьеры](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/.github/workflows/healthcheck.yaml). Его можно скопировать, немного адаптировав.

# Where?

`.github/workflows/healthcheck.yaml`

**Comment by sushidze** [comment]
@NiKuma0 @ArtemBalandin81 Какие данные использовать для переменных окружения: локальные или подтянуть данные из secrets? У меня нет доступа к secrets, но я так понимаю, там уже есть почти все, кроме 2-х последних

  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: procharity_back_db_local
  POSTGRES_USER: postgres
  DB_HOST: procharity_postgres
  DB_PORT: 5432
  APPLICATION_URL: 'http://localhost:8000/'
  HEALTHCHECK_API_URL: 'http://localhost:8000/ping'
  HEALTHCHECK_URL: 'http://localhost:8000/healthcheck'

**Comment by tWoAlex** [comment]
https://app.pachca.com/chats?thread_id=2476149
