### ISSUE TITLE
Добавить отправку токенов админу по e-mail.

### ISSUE THREAD

**Issue by ArtemBalandin81** [Studio-Yandex-Practicum/ProCharity_back_2.0#342]
# Why?

Админ становится админом по приглашению другого админа.
Приглашение высылается на почту и содержит токен.

Для управления админкой в проект добавлена библиотека [FastAPI Users](https://fastapi-users.github.io/fastapi-users/12.1/).

# How To Do?

Нужно описать эндпоинт: `/api/auth/invitation/`
Эндпоинт принимает e-mail. После выполнения всех проверок на почту высылается `Invitation token` и в БД в таблице `admin_token_requests` появляется запись с токеном.

- Логику работы эндпоинта можно поискать в старом проекте [app/auth/send_registration_invite.py](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/auth/send_registration_invite.py).
- Изучить таску по [регистрации админа](https://github.com/orgs/Studio-Yandex-Practicum/projects/5/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=48553385&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Linked+pull+requests&pane=issue&itemId=35652909), т.к. задачи пересекаются.
- Создание токена можно подсмотреть в функции `login` в `src\authentication.py` 
(на примере `access_token` и `refresh_token`).
- В FastAPI Users предусмотрен эндпоинт [request-verify-token](https://fastapi-users.github.io/fastapi-users/12.1/usage/routes/#post-request-verify-token), возможно стоит его кастомизировать.
- В проекте есть класс для отправки email `EmailProvider` в `src\core\services\email.py`.

> [!IMPORTANT]
Важно сохранить идентичность [прежней](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/auth/send_registration_invite.py) и новой api.

> [!IMPORTANT]
Схема всех [эндпоинтов](https://bot.procharity.ru/api/doc/swagger/) в прошлом проекте, которую нужно сохранить.

# How Testing It? 

Для тестирования можно:
- Вызвать эндпоинт `/api/auth/invitation/` и убедиться, что приходит [ожидаемый ответ](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/auth/send_registration_invite.py);
- Убедиться, что в БД в `admin_token_requests` появляется запись с `Invitation token` и что на почту отправляется письмо с токеном;
- Проверить, что обрабатываются исключения как в [прошлом боте](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/auth/send_registration_invite.py);
- Убедиться, что ничего не поломалось и все работает должным образом.

# Where?

`src\api\endpoints\admin.py`
`src\authentication.py`

**Comment by gorskyolga** [comment]
Реализовали в рамках задачи [#446](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/446), PR [#523](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/523)
