### ISSUE TITLE
Изменить формат сообщения email.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/ProCharity_back_2.0#368]
# Why?

Сообщение должно быть как в старом боте. 

# How To Do? 

Можно подглядеть реализацию в старом боте - том использовалась jinja.
1. Добавить jinja template.
2. Подключить template при отправки сообщений по email.

**Comment by mvolodka** [comment]
Добавлены шаблоны писем из старого проекта, описаны методы отправки ссылок для приглашения на регистрацию и сброса пароля, функция создания токена. PR: https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/388

**Comment by mvolodka** [comment]
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/388
