### ISSUE TITLE
Поменять логику отправки сообщения определенному пользователю

### ISSUE THREAD

**Issue by ArtemBalandin81** [Studio-Yandex-Practicum/ProCharity_back_2.0#391]
# Why?
Изначально эндпоинт `/api/messages/{telegram_id}` принимал `telegram_id` пользователя.
Впоследствии выяснилось, что Сайт Прочарити не знает telegram_id пользователей.
Эндпоинт был изменен под `user_id`, но не работает и требует донастройки.

# How To Do? 
- Модель `User` содержит `telegram_id` пользователя и связана с `ExternalSiteUser`, содержащей `id_hash`, который должен принимать эндпоинт.
- Модель `ExternalSiteUser` на самом деле имеет только одно обязательное поле, это `id_hash`. Поэтому нужно поправить эндпоинт отправки сообщений `/api/messages/{telegram_id}` - `telegram_id` на `id_hash` (хеш `user_id`). Его можно взять из таблицы `ExternalSiteUser`.

- Сейчас, если в эндпоинт `/api/messages/{telegram_id}` передать `id_hash` получаем ошибку:

```json
    {
      "type": "TelegramError",
      "message": "Ошибка отправки сообщения пользователю 5. Unknown error in HTTP implementation: TypeError('Object of type TelegramNotificationRequest is not JSON serializable')"
    }

```
- Есть предположение, что ошибка из `конфига pydantic модели`, но это не точно.
- Поменять документацию к этому эндпоинту, чтобы было ясно что за `id_hash` и т.п.
- Добавить метод `get_by_id_hash` в репозиторий, если еще не существует.
- Поменять схему запроса на `/messages/{telegram_id}`, чтобы вместо `user_id: int` был `id_hash: str`.
- Эндпоинт должен работать также как  `/messges/group` только `id_hash` принимать из `url`. 

# How To Test?
- Подставляя в эндпоинт `id_hash` из `ExternalSiteUser`, сообщение должно отправляться в телеграмм связанному пользователю.
- При ошибке отправки тому или иному пользователю, ответ соответствует формату:
```json
{
  "messages": [],
  "errors": [
    {
      "type": "TelegramError",
      "message": "Пользователя не найден."
    }
  ],
  "successful_rate": 0,
  "unsuccessful_rate": 1
}
```

# Where?

- [`src/api/endpoints/notification.py`](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/476e9c0f704cb29b2bbe791cab3fd2cd63ee69b6/src/api/endpoints/notification.py)
- [`src/api/services/messages.py`](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/9d1f304c1c6c2a23147b3e206fc5cc84a6182359/src/api/services/messages.py)

**Comment by gorskyolga** [comment]
Решили переделать обратно на telegram_id. 
Решено в рамках задачи https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/569
