### ISSUE TITLE
Изменить проверку авторизации / регистрации для пользователей

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#412]
# Why?

Бот отрабатывает некорректно для пользователей, у которых в БД есть telegram_id, но нет external_id. Это пользователи, общавшиеся с ботом, до того, как проверка на авторизацию / регистрацию на сайте стала обязательной. 

Такому пользователю должно передаваться сообщение о необходимости авторизоваться через сайт, кнопка меню не должна работать.

_УТОЧНИТЬ У ЗАКАЗЧИКА: Согласно Miro, сообщение должно передаваться по кнопке strat, но скорее всего нужно передавать и по кнопке menu, иначе пользователь не поймет, почему раньше бот работал, а теперь кнопка меню просто не отвечает (т.е. может не подумать, что нужно кнопку старт запустить)._

_**ОТВЕТ ЗАКАЗЧИКА**: Да, бот должен проверять соответствует ли telegram_id external_id не только при команде /start, но и при команде /menu, а также при переходе по функциям меню. При этом пользователю должно отображаться сообщение для неавторизованного пользователя с предложением авторизоваться через ЛК. Это позволит избежать ошибок бота. Если бот перестанет работать из-за сбоя в авторизации - пользователь авторизуется вновь и продолжит работу с ботом._

### Должно быть:
Основной функционал бота закрыт от пользователя до тех пор, пока он не пройдет авторизацию/регистрацию.
Неавторизованному пользователю показывается:
- Сообщение "Добро пожаловать на ProCharity! Чтобы получить доступ к боту, авторизуйтесь или зарегистрируйтесь на платформе"
- Кнопка "Войти в личный кабинет". По нажатию на кнопу пользователь переходит на страницу регистрации/авторизации сайта. Для тестового бота: http://test6.procharity.corptest.ru/registration/. Для основного бота: https://procharity.ru/registration/

### По факту 
Cейчас такой пользователь по кнопке Старт (команде /start) получает сообщение об успешной авторизации, получает доступ к кнопке "Перепроверить компетенции", а кнопка Меню (команда /menu) не работает из-за ошибки AttributeError: 'NoneType' object has no attribute 'external_id'.

# How To Do?

Добавить проверку, что на наличие external_id в обработку start_command.
УТОЧНИТЬ У ЗАКАЗЧИКА: Возможно добавить такую же проверку при обработки команды /menu.
Разобраться, каким образом происходит авторизация / регистрация и БД бота получает external_id с сайта. Понять, обработываются ли там корректно ситуации

# How Testing It? 
Проверить наличие и корректность работы кнопок Старт и Меню:
- у пользователя, которого нет в БД
- у пользователя, который есть в БД, но в таблице user нет external_id
- у пользователя, который есть в БД  и в таблице user есть external_id

Проверить, что после авторизации (привязки external_id и telegram_id), кнопки меняют своё поведение на ожидаемое. Проверить у пользователей:
- у пользователя, которого не было в БД
- у пользователя, который был в БД, но в таблице user не было external_id

# Where?
`src\bot\handlers\registration.py`

**Comment by Xalgina** [comment]
Протестировано. ОК
