### ISSUE TITLE
Изменить сообщение об успешной авторизации

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#418]
# Why?
В сообщении не хватает ссылки на личный кабинет и фразы "Навигация по боту запускается командой /menu"
Кнопки "Перепроверить компетенции" и "Открыть меню" под сообщением оставляем. 

### Должно быть:
Важно! кликабельная ссылка на Личный кабинет
Согласно схеме в Miro:
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/9e97f1c7-eb37-4fd3-a7b7-8a6070c08a59)

### По факту
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/33f85759-6227-4f94-b300-d3cade289114)

# How To Do?
...

# How Testing It? 
...

# Where?
...

**Comment by Xalgina** [comment]
Протестировано. ОК
