### ISSUE TITLE
Добавить сообщение по актуальным заданиям, если заданий нет вообще

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#419]
# Why?

### Должно быть:
При вызове кнопки меню "Посмотреть актуальные задания" выводится список заданий. Если заданий нет вообще (т.е. вообще нет заданий в БД по категориям пользователя), то должен выводится такой текст:
"Актуальных заданий по твоим компетенциям на сегодня нет."
Согласно схеме Миро:
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/9708fc84-e778-4b8b-b150-bc57d492e991)

### По факту 
Обработка данного случая не предусмотрена в коде. Вместо этого выводится сообщение для случая, когда задания в БД есть, но пользователь их все посмотрел.

# How Testing It? 
Подписать пользователя на категорию, у которой нет заданий в БД, и нажать "Посмотреть актуальные задания".

# Where?
src\bot\handlers\tasks.py в view_task_callback()

**Comment by Xalgina** [comment]
Протестировано. ОК
