### ISSUE TITLE
Добавить сообщение по обратной связи

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#422]
# Why?
При нажатии кнопки "Написать в службу поддержки" должно отображаться сообщение.

### Должно быть:
Согласно схеме в Miro:
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/f36be0da-d087-4d07-ba5f-612b6d3a5868)

### По факту
Нет сообщения, сразу появляется поп-ап с формой.

# How To Do?
...

# How Testing It? 
...

# Where?
...

**Comment by Xalgina** [comment]
Протестирован текст сообщения. Все ОК
