### ISSUE TITLE
Добавить кнопку "Посмотреть актуальные задания" при подключении подписки

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#428]
# Why?
Если пользователь включает подписку, то появляется сообщение и кнопка "Вернуться в меню". Нужно добавить кнопку "Посмотреть актуальные задания".

### Должно быть:
Сообщение и две кнопки

### По факту
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/3ab67b1a-7c7f-457b-a139-2eae51771e81)

# How To Do?
...

# How Testing It? 
...

# Where?
...

**Comment by Xalgina** [comment]
**Протестировано. Реализовано верно.**

При нажатии кнопки "Подписаться на задания" пользователь видит кнопки:
"Посмотреть актуальные задания"
"Вернуться в меню"

Сообщение
"Подписка включена!

Теперь ты будешь получать новые задания от фондов по выбранным компетенциям."
