### ISSUE TITLE
Рефакторинг изменения категорий

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#445]
### Why

Функция view_old_categories_callback имеет логику, практически идентичную с функциями all_right_categories_callback и confirm_categories_callback (есть отличия только в тексте сообщения и кнопках), каковую логику надо вынести куда-то отдельно и использовать во всех трёх функциях.

Нужно поправить докстринг confirm_categories_callback. Записью категорий в БД занимается другая функция (select_subcategory_callback).

По информации от заказчика:
1. Подписка на рассылку должна включаться при изменении категорий (сейчас так и есть, так и нужно оставить).
2. Если в экране просмотра текущих категорий, пользователь нажал "Все верно", то нужно сразу возвращаться его в главное меню, без повторения сообщения про категории.

Стоит поменять confirm_categories_callback (вызывать из нее функцию с выводом сообщения о компетенциях или попробовать перенести установку has_mailing в другое место, чтобы функции стали одинаковыми за счёт этого).

### Where
src/bot/handlers/categories.py

**Comment by ASTimch** [comment]
Судя по пожеланиям заказчика all_right_categories_callback  вообще не нужна. Нажатие на кнопку "Все верно" будет сразу переводить в главное меню

**Comment by Xalgina** [comment]
**Протестировано - текст сообщения верен.**

При проверке компетенций и после их изменения пользователь должен видеть следующее сообщение:

"Отлично!

Теперь сюда будут приходить уведомления о новых заданиях в следующих категориях:

🎓 Работа с текстами
🎓 Подкатегория в Алгоритмы

А пока можешь посмотреть актуальные задания."

**Comment by Xalgina** [comment]
**Протестировано. ОК**

Если в экране просмотра текущих категорий, пользователь нажал "Все верно", то он сразу возвращается в главное меню, без повторения сообщения про категории.
