### ISSUE TITLE
Исправить баг: отображение списка заданий после актуализации заданий

### ISSUE THREAD

**Issue by Nikolas1440** [Studio-Yandex-Practicum/ProCharity_back_2.0#448]
Баг возникает при просмотре заданий списком по кнопке "Посмотреть актуальные задания".
Если пользователь посмотрел частично или полностью задачи в выбранных категориях, затем через эндпоинт бота произошло обновление заданий, то пользователь видит задания некорректно.

Например:
1. В категории, на которую подписан пользователь, есть четыре актуальных задания. Пользователь посмотрел задания 1, 2 и 3. Далее ему предлагается выбор, посмотреть ещё одно задание или вернуться в меню. 
2. Произошло обновление заданий. Задание 2 стало неактуальным. 
3. Список актуальных заданий для волонтёра стал 1, 3 и 4. Задания отображаются по три и бот считает, что волонтёр уже видел первые три задания. Если пользователь нажмет кнопку "Продолжить просмотр", то бот отобразит сообщение "Ты посмотрел все актуальные задания", хотя волонтёр не видел задание 4.

Нужно:
- разобраться, как формируется список заданий для отображения пользователю;
- предусмотреть "перезапуск" списка заданий при их обновлении;
- переделать сортировку заданий в списке, сначала показывать новые / обновленные задания, а в конце списка - старые;
- добавить еще один уровень сортировки для заданий (по id), т.к. при обновлении заданий списком у части заданий одинаковое время обновления и в результате сортировка случайная.

**Comment by gorskyolga** [comment]
Эту задачу можно решить в рамках PR по задачам [471](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/471) и [469](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/469), т.к. они сильно связаны. Можно решать отдельно, но тогда при решении первых двух задач понимать, что далее нужно будет решать этот баг.

Для решения бага с отображением заданий при их актуализации можно использовать переменную viewed_all (как реализовал Коля для другого бага), но мне опять же не хочется хранить список просмотренных заданий. Альтернативное решение, которое я придумала, - хранить в контексте две переменные: 1) количество актуальных заданий для пользователя и 2) время обновления задания обновленного / созданного позже всех из актуальных заданий для пользователя. Если сравнивать эти переменные из контекста с их значениями на момент просмотра, то можно отследить, что было обновление / создание и удаление заданий.

Получается, есть несколько вариантов решения задачи: Колин, мой и возможно еще какие-то. Нужно выбрать, какое из них лучше реализовывать.

**Comment by eugemos** [comment]
У предложенного варианта есть подводные камни:
1. Способ отображения должен годиться для всех возможных вариантов изменения в списке задач для данного пользователя, а не только для случая актуализации. А вот для #471 он уже на так хорош, так как при изменении категорий пользователя у него в списке могут появиться задачи, которые были давно обновлены, и которые будут восприниматься как уже просмотренные. Тут, конечно, можно анализировать ещё и время присвоения пользователю категории, к которой относится задача, но сложность растёт.
2. Время обновления задания не даёт однозначной позиции в списке заданий, так как может быть одинаково для нескольких заданий, часть из которых уже просмотрена, а другая нет. Как тут быть непонятно.

Возможно, я не так понял задумку. Мне, например, не понятно, зачем нам нужно количество актуальных заданий для пользователя хранить. Кажется, что достаточно и временной отметки. Тогда стоит написать более подробно, как по этим двум переменным понять, с какой точки надо продолжить отображение задач пользователю, и как их нужно изменять.

И, наконец, чем так уж плохо множество всех `id`, есть опасения за его размер?

**Comment by gorskyolga** [comment]
Допустим, мы вводим две переменные tasks_amount (количество заданий в выборке заданий для пользователя) и last_task_update (наибольшее значение в поле updated_date по выборке заданий для пользователя). Нужно сохранить их значения на момент последнего просмотра и сравнивать с их же текущими значениями перед отображением следующей порции заданий. Если изменилась tasks_amount, значит либо удалили часть заданий, либо добавили новые. Если добавили и удалили одинаковое количество заданий и в результате tasks_amount не изменилась, то изменилась last_task_update.

Соответственно сочетание этих переменных позволяет понять, что произошло обновление заданий, и перезапустить их отображение сначала.

1. При изменении категорий задания также начинают показываться сначала. Только триггером выступает сама смена категорий.
2. То, что у нескольких заданий одинаковое время обновления, не влияет на решение, так как нас интересует максимальное время обновления.
3. Чтобы корректно отображать задания с одинаковым временем обновления в списке, можно ввести второй уровень сортировки, например, id задания.
4. Хранение множества всех id смущает из-за потенциально большого размера и как следствие замедления работы. Я не уверена, что это так уж сильно повлияет. Две первые задачи, которые решал Коля, точно можно было решить без их хранения (управлением номером отображаемой страницы). Для решения этой задачи можно добавить, но не знаю, стоит ли.

**Comment by eugemos** [comment]
@gorskyolga , спасибо за пояснение! Я понял теперь зачем две переменных.
Но перезапуск списка мне что-то не нравится. Ведь если мы исходим из возможности списка большого размера, то давай представим ситуацию, что пользователь просмотрел значительную часть списка и после этого он перезапустился, причём пользователь, возможно, даже никак не будет уведомлен об этом. Он вынужден будет просматривать список с начала и, возможно, даже не будет понимать, почему это произошло, и сочтёт это за глюк - и это будет плохой user experience.

Я предлагаю попробовать другой вариант. Надо составить из заданий для пользователя последовательность таким образом, чтобы новые (для данного пользователя) и обновлённые задания всегда помещались (перемещались) после тех заданий, которые уже просмотрены (наверное, в конец всей последовательности), тогда хранить надо будет только "указатель" на последнюю просмотренную задачу. При этом, перезапускать список будет не надо, а повторно попадаться будут только лишь те задачи, которые были обновлены. Для критерия упорядочивания, наверное, можно будет взять максимум из времени обновления задачи и присвоения её категории данному пользователю.

Как тебе такая идея?

**Comment by gorskyolga** [comment]
Думаю, идея классная.
Если вместо использования последовательности заданий, возвращаемой get_tasks_limit_for_user, будет использоваться другая последовательность, сортированная, как ты описал, по времени обновления задания и времени создания записи в users_categories, то это решит баг и с обновлением заданий и с обновлением категорий.
Хотя я и согласовала с заказчиком перезапуск заданий при обновлении заданий / категорий, но если сможем реализовать без перезапуска, то будет гораздо лучше.
