### ISSUE TITLE
Убрать кнопку "Нет моих компетенций"

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#451]
При изменении компетенций есть кнопка "Нет моих компетенций". Сейчас она не делает ничего. Заказчик попросил её убрать.

Нужно убрать кнопку и подчистить неиспользуемый код.

**Comment by Yohimbe227** [comment]
Убрал кнопочку, вроде там все в одной строке. Заодно убрал нехорошие значения по умолчанию в соседних функциях.
