### ISSUE TITLE
Баг: архивные категории продолжают числиться за пользователями и нарушают логику работы бота при отрисовке кнопок

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#454]
# Why?

Если пользователь подписался на категорию, а она стала архивной, то подписка остается висеть в БД и бот некорректно отображает ее наличие:
- при старте в приветствии (на скрине старая версия формата сообщения);
- при цвете галочек.

![Image](https://user-images.githubusercontent.com/105808126/278210938-b4ab65c2-3fa7-4b60-adc9-6270e42ac23a.png)

![Image](https://user-images.githubusercontent.com/105808126/278210948-835bb9e4-868e-4f36-b50c-f405dc926588.png)

# How To Do?
- настроить фильтры, которые не будут учитывать архивные категории
- изменить логику отрисовки кнопок в боте

# Where?

`src\bot\keyboards`
`src\bot\handlers\categories`

**Comment by ASTimch** [comment]
В тестовой БД возможна ситуация, когда родительская категория числится архивной, а ее дочерние - не архивные. 
Считаем, что в рабочей БД такой неконсистентности не будет или все-таки, следует всегда еще анализировать и "архивность" родительской категории и для "архивной" родительской категории считаем "архивной" и дочернюю?

**Comment by gorskyolga** [comment]
Проверила, как работает обновление категорий на тестовом сайте из учётки админа.

Эндпоинт для обновления категорий вызывается в двух случаях: при создании категории / подкатегории и при их удалении. При "деактивации" и "активации" категории и подкатегории и даже при переносе подкатегории в другую категорию эндпоинт не вызывается.
Если создавать категорию или подкатегорию, то в БД бота они появляются сразу. Если удалять подкатегорию, то она в БД бота архивируется сразу. Если удалять категорию, то в БД бота архивируются подкатегории, которые к ней относились, при этом родительская (удалённая через админку сайта категория) продолжает отображаться как активная до момента следующего запроса к эндпоинту.

Таким образом ситуация, когда родительская категория архивная, а дочерние нет, невозможна. Обрабатывать её дополнительно не нужно.

update:
Но если такая обработка уже предусмотрена в решении, то убирать её не нужно.
