### ISSUE TITLE
Создать эндпоинт API для регистрации / обновления фондов

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#460]
Нужно создать эндпоинт API `api/auth/external_fund_registration`.
Он должен работать по аналогии с `api/auth/external_user_registration`:
- принимать все те же поля кроме specializations, т.е. user_id, id_hash, first_name, last_name, email.
- при post-запросе к эндпоинту в БД должна появляться / обновляться запись в таблице external_site_users с ролью fund.
- если пользователь user, привязанный к external_site_user, существует, то роль fund должна прописываться для пользователя в таблице users.

В рамках этой задачи также нужно:
- исправить обработку эндпоинта `api/auth/external_user_registration` таким образом, что если пользователь user, привязанный к external_site_user, существует, то роль volunteer прописывается для пользователя в таблице users;
- проверить, что при обращении по очереди к этим двум эндпоинтам с данными одного и того же external_user роль пользователя меняется в таблице external_site_users и в таблице users, если этот external_user привязан к какому-нибудь user.

**Comment by eugemos** [comment]
Наверное, если роль пользователя меняется с волонтёра на фонд, надо также обнулить категории на всякий случай, вдруг они там были заданы.
