### ISSUE TITLE
Баг: при обновлении существующего задания сообщение о задании не приходит в бот

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#470]
При обращении внешнего сайта к эндпоинту `api/tasks` (post-запрос) актуализируется список заданий.
Если пользователь подписан на категорию и подписка на рассылку включена, то он должен получать сообщение в бот о новом задании или об обновлении старого задания (например, изменении бонусов).
Сейчас приходят сообщения о новых заданиях, но не приходят сообщения при обновлении существующих задач. 

В данной задаче речь идет о рассылке через бот, а не о списке задач, который отображается по кнопке "Посмотреть актуальные задания".

**Важно:** Перед тестированием необходимо очистить локальную БД от фейковых юзеров (оставить только свой ТГ-аккаунт), чтобы случайно не отправить сообщение реально существующим пользователям Телеграм.

Нужно:
- разобраться в работе эндпоинта при post-запросе;
- изменить работу actualize_tasks и actualize_objects таким образом, чтобы приходили сообщения при обновлении задач.

**Comment by ASTimch** [comment]
Сейчас алгоритм работы actualize_tasks следующий:
1) алгоритм предполагает, что POST запрос присылает все актуальные задачи на текущий момент (вызывает кучу вопросов такой подход. Может быть лучше иметь ендпойнт для обновления каждой задачи?)
2) Все задачи, id которых нет в списке POST запроса объявляются архивными
3) Все задачи, id которых имеются в базе обновляются данными из запроса
4) Все задачи, id которых еще не содержится в базе создаются (и для них осуществляется рассылка)

Т.е. если мы хотим сделать рассылку по обновленным заданиям, то необходимо:
1) Определить список триггерных полей изменение которых должно приводить к повторной рассылке
2) Для каждого задания из пост запроса необходимо сравнить каждое из триггерных полей с текущим значением и при несовпадении хотя бы одного из них, пометить эту задачу как обновленная для рассылки.
Эти сравнения по каждому полю каждого задания выглядят очень криво.

Доп вопрос: при рассылке измененных заданий (а не новых) их нужно как-то отдельно помечать, что это задание не новое, а измененное?
