### ISSUE TITLE
Учесть в авторизации в боте наличия ролей волонтера и фонда (и возможной смены роли)

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#484]
1. Если у пользователя отсутствует роль в таблице users в БД, то пользователь не авторизован и функционал бота должен быть закрыт.

2. Если пользователь выполняет команду `/start <id_hash>` и привязывается к другому личному кабинету (в том числе со сменой роли с волонтера на фонд и обратно), то его данные в БД должны обновляться. Сейчас если у нового external_site_user нет категорий, то они не обновляются в БД. Соответственно у пользователя могут остаться категории от предыдущего external_site_user в таблице users_categories.

3. Также нужно проверить корректность обновления полей email, first_name, last_name, role при привязке к другому external_site_user.

**Comment by eugemos** [comment]
Вопрос по п. 1. 
Если пользователь с неизвестной ролью считается неавторизованным, то мы ему можем вывести сообщение с предложением зарегистрироваться на сайте. Ничего другого у нас пока не предусмотрено на схеме. Не собьёт ли такое сообщение пользователя с толку, ведь он может быть вполне себе зарегистрирован, только лишь роль не задана. Может, стоит для такого случая какое-нибудь другое сообщение выводить, типа "Ваша роль нам неизвестна, зайдите ещё раз через сайт"? Или бог с ним?

**Comment by gorskyolga** [comment]
> Вопрос по п. 1. Если пользователь с неизвестной ролью считается неавторизованным, то мы ему можем вывести сообщение с предложением зарегистрироваться на сайте. Ничего другого у нас пока не предусмотрено на схеме. Не собьёт ли такое сообщение пользователя с толку, ведь он может быть вполне себе зарегистрирован, только лишь роль не задана. Может, стоит для такого случая какое-нибудь другое сообщение выводить, типа "Ваша роль нам неизвестна, зайдите ещё раз через сайт"? Или бог с ним?

Я думаю, сообщение не должно различаться для разных случаев.
Сообщение, которое сейчас используется, предлагает пользователю авторизоваться / зарегистрироваться. Его по-хорошему нужно расширить указаниями, что нужно привязать бота в настройках ЛК. Напишу такой вопрос в списке для заказчика, если у них будет желание, то поменяем текстовку сообщения.
