### ISSUE TITLE
Изменить настройки рассылки обновленного задания

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#494]
В рамках [PR](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/480) были добавлены TRIGGER_MAILING_FIELDS для определения полей задания, при обновлении которых задание должно рассылаться волонтерам повторно.

1. Необходимо изменить настройки таким образом, чтобы задание рассылалось повторно при изменении только полей "deadline" и "category_id".
По информации от заказчика, в существующем задании может быть изменен только срок сдачи, но лучше перестраховаться и использовать в настройках и "category_id", чтобы существующее задание в принципе рассылалось волонтерам, подписанным на новую категорию, хотя бы один раз.

2. Также нужно изменить шаблон для обновленного задания. Он должен быть тот же, который используется для нового задания.

3. К сообщению о новом / обновленном задании, которое приходит в рамках рассылки, нужно добавить кнопку "Посмотреть задание", открывающую вэб-апп. Таким образом сообщение о задании должно быть одинакового формата для рассылки заданий и при просмотре актуальных заданий списком по кнопке "Посмотреть актуальные задания".

**Comment by ASTimch** [comment]
Я понимаю, что мы должны делать как хочет заказчик, но в конкретно в этом случае, я не соглашусь с тем, что обновленное задание должно быть точно таким же как новое. В данном случае у меня как пользователя будет вызвать дежавю (недоумение) тот факт, что при обновлении дедлайна какого-то из заданий я его буду видеть повторно (если я его до обновления прочел и не откликнулся).
Может быть все-таки добавить заголовочек "дедлайн задания изменен", учитывая что у нас по настройкам может меняться только дедлайн.
По крайне мере примерно такое поведение я наблюдал на одном сайте фриланса, на котором работал лет 5. Там для обновления дедлайна уже имеющегося задания это задание попадало опять в рассылку на почту и в личный кабинет, но сам факт изменения дедлайна (или стоимости задания) указывался в заголовке. У нас такая возможность уже реализована. Можем конечно ею не пользоваться, но с точки зрения юзабилити это может быть не лучшее решение.

**Comment by gorskyolga** [comment]
Добавила в вопросы для заказчика.
Если оставлять еще триггером изменение категории, то тогда нужно доп.проверку вводить, что это именно дедлайн поменялся, а не категория. Хотя изменение категории - это вообще особенное изменение, потому что для пользователей новой категории - это по сути новое задание, а не обновленное.

**Comment by ASTimch** [comment]
Можно просто заголовок добавить: "Задание обновлено"

**Comment by gorskyolga** [comment]
> Можно просто заголовок добавить: "Задание обновлено"

Получили ответ от заказчика:
1. Ситуация смены категории у существующего задания невозможна. У задания может поменяться только срок сдачи. 
2. Для обновленного сообщения в формате должно быть различие. По заданиям с обновленным сроком сдачи в строке со сроком добавить красный восклицательный знак: "❗️**Срок**: дата".
