### ISSUE TITLE
Диспетчеризация рассылки сообщений

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#498]
Отправка сообщений должна происходить таким образом, чтобы бот не был заблокирован Телеграмом.
Может стоить добавить брокер?

Также:
Пользователи, у которых бот забанен не должны включаться в рассылки (массовые, индивидуальные, заданий)?
В TelegramNotification в __send_message этот случай специально не обрабатывается.

Можно посмотреть, как это было реализовано [в первой версии проекта](https://github.com/ProCharity/ProCharity_bot/blob/develop/bot/messages.py).

**Comment by ASTimch** [comment]
В текущей версии для создания бота уже используется rate_limiter(AIORateLimiter()) со значениями по умолчанию. В нем уже реализованы лимиты 30 сообщений в секунду (при необходимости их можно менять параметрами AIORateLimiter)

**Comment by gorskyolga** [comment]
> В текущей версии для создания бота уже используется rate_limiter(AIORateLimiter()) со значениями по умолчанию. В нем уже реализованы лимиты 30 сообщений в секунду (при необходимости их можно менять параметрами AIORateLimiter)

Получается, диспетчеризация уже есть и по этой задаче нужно только учесть, чтобы в выборку сообщений не попадали пользователи, заблокировавшие бот?

**Comment by ASTimch** [comment]
Да. Диспетчеризация уже есть.
Как я понял, сейчас вообще не анализируется забанен бот или нет. Может быть эту задачу получится решить в процессе #495

**Comment by gorskyolga** [comment]
Не уверена, что это стоит решать в рамках [495](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/495). Если изменений в ветке не слишком много будет понамешано, то можно.
