### ISSUE TITLE
Доработать вэб-апп для отображения description через api

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#511]
Сейчас в вэб-апп передаются поля через query-параметры и среди них есть поле description, длина которого может быть несколько тысяч символов.

Нужно: 
1. Добавить api для получения информации о задании по task_id.
- Имя эндпоинта `api/tasks_details/{task_id}`, так как уже существует эндпоинт `api/tasks/{user_id}`.
- Эндпоинт должен работать только на get и возвращать поля description и deadline.
- Доступ к эндпоинту должен быть у всех без передачи токена.
- Тэг как для остальных эндпоинтов категорий и заданий: tags=["Content"].

2. Изменить параметры, передаваемые в вэб-апп. Нужно передавать task_id и версию api (ROOT_PATH из settings.py).

**Comment by eugemos** [comment]
Предлагаю не ограничивать информацию, получаемую из `api/tasks_details/{task_id}`, полями `description` и `deadline`,  и передавать то же самое, что и через `api/tasks`. У этого есть два плюса:
- не нужно будет создавать ещё одну схему ответа;
- если вебапу в будущем понадобится ещё какая-нибудь информация, ничего менять нужно не будет, уже всё у него есть.

**Comment by gorskyolga** [comment]
Да, хорошая идея.
Есть только один нюанс. Новый эндпоинт должен быть открытым для всех, чтобы вэб-апп корректно работал. Есть вероятность, что в вэб-версии Телеграм через инструменты разработчика можно будет увидеть все поля. И если просто обратиться к эндпоинту, то все поля будут видны. Хотя в этом может и нет ничего страшного, т.к. страницы с заданиями на платформе открыты для просмотра всем без регистрации.

**Comment by gorskyolga** [comment]
Пока нужно делать так, как проще. А когда получим пример поля descrrption и решим, как его обрабатывать и хранить, то и будем думать, как с эндпоинтом быть.
