### ISSUE TITLE
Добавить эндпоинт для удаления пользователя внешнего сайта

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#516]
Пользователь может быть удален с внешнего сайта.

1. Нужно предусмотреть мягкое удаление external_user из БД бота. Для этого в модель ExternalSiteUser нужно добавить поле is_archived со значением по умолчанию False.
При добавлении поля в модель и проверке созданной миграции нужно ориентироваться на поле is_archived для заданий и категорий:
- ContentBase в src\core\db\models.py;
- поиск по "is_archived" в src\core\db\migrations\versions\2024-01-11_16.21.54_v2_0.py (в этой миграции поле не создавалось, а изменялось существующее).

2. Добавить метод DELETE для существующих эндпоинтов "/external_user_registration" (для волонтеров) и 
"/external_fund_registration" (для фондов).
В тело запроса должно передаваться user_id (для бота это external_id в таблице external_site_users).

3. Эндпоинт должен обрабатывать ситуации:
- отсутствует токен авторизации в запросе или неверный токен;
- несоответствие схеме;
- user_id не найден в БД бота (это возможная ситуация, т.к. пользователь мог не подключать бот; скорее всего эндпоинт будет вызываться при удалении пользователя внешнего сайта без проверки, подключал ли он бот);
- user_id найден в БД, мягкое удаление состоялось. Можно вернуть статус 204 или 200, что будет проще.

4. При обращении к эндпоинту для пользователя нужно:
- изменить is_archived в таблице external_site_users на True;
- разорвать связь телеграм-юзера с external_user, если она существует.

5. Также нужно предусмотреть запрет на привязку к удаленному external_user (с is_archived = True) по команде `start id_hash`.

**Примечание:**
Решили пока не реализовывать проверку случая, если user_id найден в БД бота, но роль пользователя не соответствует эндпоинту (что через эндпоинт для волонтеров не пытаются удалить фонд и наоборот).

**Comment by eugemos** [comment]
Есть вопросы:
- по п. 2:
  - не стоит ли идентификатор удаляемого объекта передавать в пути, т.е. `/external_user_registration/{user_id}`, а не в теле запроса, аналогично тому, как это мы собираемся делать для задач?
- по п. 3:
  - а что делать, если объект уже удалён ранее, это ошибка или нет?

**Comment by gorskyolga** [comment]
По п. 2: Да, идентификатор удаляемого объекта стоит передавать в пути для единообразия.
По п. 3: Да, это ошибка. Нужно возвращать такой же статус, как для несуществующего id.

**Comment by gorskyolga** [comment]
Update по задаче:
нужно сделать только один эндпоинт для удаления и волонтеров, и фондов (`/external_user_registration/{user_id}`).
