### ISSUE TITLE
Добавить метод delete эндпоинту `api/task/{task_id}`

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#525]
При delete-запросе на эндпоинт `api/task/{task_id}` должно архивироваться задание с указанным task_id (поле is_archieved = True), если task_id существует.
Тело запроса пустое. Доступ только по токену основного сайта.
Можно в ответ вернуть статус 204 или 200, что будет проще.

**Comment by eugemos** [comment]
У нас есть эндпойнт `GET(task_detail/{task_id})` для получения информации об отдельной задаче. Не стоит ли его заодно перенести на `task/{task_id}`? Структура API будет аккуратнее и меньше роутеров будет.

**Comment by gorskyolga** [comment]
Стоит, и это уже сделано в рамках другой задачи. В ветке develop эндпоинт для вэб-аппа уже на `task/{task_id}`.

**Comment by gorskyolga** [comment]
Там может стоит отрефакторить название роутеров.
Сейчас есть:
- task_router (с префиксом tasks, доступ по токену);
- task_detail_router (с префиксом task, доступ свободный);
- И еще один должен добавиться (с префиксом task, доступ по токену), где будут методы delete, post, put.

Так что если есть видение, как сделать структуру API лучше, то можно реализовать.
Главное, помнить, что `task/{task_id}` должен быть на get для вэб-аппа открытым, а всё остальное доступно только по токену.
