### ISSUE TITLE
Закрыть доступ к вэб-аппу по заданию, если пользователь не авторизован или задание архивное

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#537]
Сейчас пользователи телеграм без авторизации в боте, у которых в чате сохранились сообщения с заданиями, могут нажать кнопку "Посмотреть задание" под такими сообщениями и увидеть вэб-апп.

Нужно предусмотреть "прослойку" между нажатием кнопки и вызовом вэб-аппа.

Такая прослойка должна:

1. Проверять авторизацию пользователя (в коде для этого есть декоратор registered_user_required).
Если пользователь неавторизован, то выводить в чат стандартное сообщение, предусмотренное для этого случая.

2. Проверять, что задание, для которого вызывается вэб-апп, не стало архивным.
Если задание архивное, то нужно выводить поп-апп с текстом "Задание неактуально".

Если пользователь авторизован и задание актуально, то должен вызываться вэб-апп, как предусмотрено в боте сейчас.

**Comment by eugemos** [comment]
Посмотрел все способы запуска вебапа, указанные [здесь](https://core.telegram.org/bots/webapps#implementing-mini-apps).
Получается, что у бота нет способа самому запустить вебап. Можно только разместить ссылку на него в чате или меню и ждать, когда пользователь её активирует. И тогда клиент Телеграма сам запустит вебап, но уже без участия бота.
Не получается, в общем, прокладку по-простому сделать.

Есть такая идея: вместо ссылки на вебап подсунуть ссылку на специальный эндпойнт API бота, который будет все проверки выполнять и, если всё ок, то редиректить на настоящий вебап. Но есть трудность с проверкой этой идеи из-за того, что Телеграм в качестве ссылки на вебап принимает только URL с протоколом https. Есть мысли, как это можно локально организовать?

**Comment by gorskyolga** [comment]
Мне кажется, если более-менее простого способа нет, то будет лучше пока отложить эту задачу. 
Проверку, что задача стала архивной, можно реализовать на стороне фронта вэб-аппа. А закрытие вэб-аппов от неавторизованных пользователей не настолько критично для заказчика.

Если потом решим реализовать, то проверить такой специальный эндпоинт проще всего будет с помощью деплоя на тестовый сервер.
