### ISSUE TITLE
Добавить докстринг в UserStatus

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#564]
Нужно добавить в UserStatus докстринг с описанием значений статусов на русском (просто для прозрачности, использовать их в коде скорее всего не будем):

- Для волонтера:
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/93aa3acb-1aa9-4727-9f75-9cf3cd200ec3)

- Для фонда:
![Image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/2bd9085f-8a16-4ed0-9d18-895b98994cbe)

**Comment by StriderDunedain** [comment]
@gorskyolga Что-то не могу найти `UserStatus`. Что это?

**Comment by gorskyolga** [comment]
Посмотри в "src\core\enums.py".

**Comment by StriderDunedain** [comment]
Для ясности: этот докстринг нужно добавить в `UserRoles`?

**Comment by gorskyolga** [comment]
Нужно добавить докстринг в UserStatus.
Сейчас он такой: "Класс с доступными статусами модерации пользователей". Нужно добавить фразу типа 'Расшифровки доступных статусов: NEW_VOL - "Новый", ...'.
