### ISSUE TITLE
Починить эндпоинт api/tasks для get-запросов

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#567]
Эндпоинт `api/tasks` не работает на get-запрос на тестовом сервере и на продакшн-сервере.
Ошибка возникает из-за того, что в БД есть задания, которые не проходят валидацию по схеме TaskResponse.
Для БД на тестовом сервере по некоторым заданиям нет значений в полях, которые являются обязательными на уровне схемы:
- deadline;
- category_id.
Нужно разрешить этим полям принимать значение NULL (None ) на уровне схемы TaskResponse.

Доступа к БД на продакшн нет, но скорее всего там проблема в этих же полях и возможно также есть записи, по которым не заполнены какие-то другие обязательные поля. Исправление схем под БД на продакшн, если оно потребуется после релиза, будет отдельной задачей.

**Comment by StriderDunedain** [comment]
А как правильно тестировать?

**Comment by gorskyolga** [comment]
1. Повторить ошибку на локальной БД. Для этого в БД удалить значения полей deadline и / или category_id у части заданий. Проверить, что в ветке develop возникает ошибка при обращении с get-запросом на эндпоинт `api/tasks`.
2. Перейти в ветку с фичей и проверить, что ошибка при обращении с get-запросом на эндпоинт `api/tasks` не возникает, а вместо нее эндпоинт работает как ожидается.

Можно обращаться не к `api/tasks`, а к `api/task/{task_id}` по конкретной задаче, у которой удалены значения в полях deadline и / или category_id.
