### ISSUE TITLE
Починить эндпоинт "api/messages/{telegram_id}"

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#569]
Эндпоинт должен отправлять сообщение пользователю по telegram_id, если пользователь с таким telegram_id есть в БД бота.
Сейчас эндпоинт работает некорректно. В частности пытается передать telegram_id в функцию, принимающую id_hash.

Нужно починить эндпоинт.
Для этого нужно создать новый метод в TelegramNotificationService. Метод, который сейчас используется при обработке эндпоинта, изменяться не должен, так как он используется для другого эндпоинта.

Новый метод для отправки сообщения по telegram_id:
- должен проверять, что пользователь с таким telegram_id есть в БД бота. Отправка сообщения пользователям, telegram_id которых нет в БД бота, запрещена.
- если telegram_id найден, должен вызывать send_message из TelegramNotification.

### Where?
src\api\endpoints\notification.py
src\api\services\messages.py

**Comment by Xalgina** [comment]
Функционал был протестирован в рамках [PR](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/578).
