### ISSUE TITLE
[BUG] Пользователь остается авторизованным, если разорвать связь между users и external_site_users командой UPDATE

### ISSUE THREAD

**Issue by Xalgina** [Studio-Yandex-Practicum/ProCharity_back_2.0#580]
Бот работал некорректно для пользователей, у которых в БД есть telegram_id, но нет external_id. Это пользователи, общавшиеся с ботом, до того, как проверка на авторизацию / регистрацию на сайте стала обязательной. Такой пользователь по кнопке Старт (команде /start) получал сообщение об успешной авторизации и доступ к кнопке "Перепроверить компетенции", а кнопка Меню (команда /menu) не работала.

- Проверить чтобы бот корректно работал с авторизованными пользователями
- Проверить чтобы бот выдавал неавторизованным пользователям сообщение о необходимости авторизоваться

**Comment by gorskyolga** [comment]
Функционал реализовали в рамках:
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/412
