### ISSUE TITLE
Рефакторинг CustomFastAPIUsers

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#589]
При подключении библиотеки FastAPI Users к проекту класс CustomFastAPIUsers был создан по аналогии с FastAPIUsers, но только с двумя переопределенными методами get_register_router и get_auth_router.
При этом CustomFastAPIUsers наследуется не от FastAPIUsers, а от Generic[models.UP, models.ID]. Скорее всего код FastAPIUsers был целиком скопирован в CustomFastAPIUsers, а затем из него удалялись неиспользуемые части.
Нужно проверить, можно ли наследовать CustomFastAPIUsers от FastAPIUsers и удалить из него "authenticator: Authenticator" и init. Кажется, что эта часть стандартная и может не переопределяться.

### Where
CustomFastAPIUsers в `src\api\fastapi_admin_users.py`

**Comment by StriderDunedain** [comment]
### Что происходит:
Как оказалось, заменить кастомный класс на встроенный не так просто. Сейчас он переадресует встроенный метод `get_register_router` на кастомную функцию. Полагаю, именно поэтому было отдано предпочтение дженерику (а так же, возможно, чтобы выдавать лишь тот функционал, который нужен).
### Возможное решение:
В принципе все можно решить так (не убирая `get_register_router` - у него кастомная логика), но я не уверен, можно ли так наследовать `FastAPIUsers` (без `Generic[...]` ругается). А так все запускается без проблем:
```python
class CustomFastAPIUsers(FastAPIUsers, Generic[models.UP, models.ID]):
    def get_register_router(self, user_schema: Type[schemas.U], user_create_schema: Type[schemas.UC]) -> APIRouter:
        return get_register_router(self.get_user_manager, user_schema, user_create_schema)
```
### Траблы:
1. Вопрос с тем, можно ли так наследовать `FastAPIUsers`. Ни разу не видел - хочется более экспертное мнение
2. Немного беспокоит то, что до того, как сократить код, додуматься легко, но по какой-то причине был выбран именно дженерик (возможно, как писал выше, связано с ограничением функционала) - тоже хочется более опытный взгляд

**Comment by StriderDunedain** [comment]
### Что происходит
Как оказалось, заменить кастомный класс на встроенный не так просто. Сейчас он переадресует встроенный метод `get_register_router` на кастомную функцию. Полагаю, именно поэтому было отдано предпочтение дженерику (а так же, возможно, чтобы выдавать лишь тот функционал, который нужен).
### Возможное решение
В принципе все можно решить так (не убирая get_register_router - у него кастомная логика), но я не уверен, можно ли так наследовать `FastAPIUsers` (без `Generic[...]` ругается) и почему такое очевидное решение не было сразу реализовано. А так все запускается без проблем:
```python
class CustomFastAPIUsers(FastAPIUsers, Generic[models.UP, models.ID]):
    def get_register_router(self, user_schema: Type[schemas.U], user_create_schema: Type[schemas.UC]) -> APIRouter:
        return get_register_router(self.get_user_manager, user_schema, user_create_schema)
```
### Траблы
Хоть и не думаю, что с этим будут проблемы, есть вопрос с тем, можно ли так наследовать `FastAPIUsers`. Ни разу не видел - хочется более экспертное мнение

**Comment by gorskyolga** [comment]
Да, как и написано в описании задачи, get_register_router и get_auth_router в CustomFastAPIUsers кастомные.

Предпочтение Generic скорее всего не "отдавалось". Я думаю, что при добавлении в проект FastAPI Users весь код класса FastAPIUsers просто скопировали, назвали его CustomFastAPIUsers, вырезали ненужные части, а get_register_router и get_auth_router переопределили. Поэтому там наследование от Generic[models.UP, models.ID], как и в классе FastAPIUsers. Плюс на тот момент подключать другие роутеры еще не требовалось.

Попробовала отнаследоваться от FastAPIUsers. Ты получаешь ошибку "TypeError: <class 'src.api.fastapi_admin_users.CustomFastAPIUsers'> is not a generic class"?
