### ISSUE TITLE
Поменять сообщение при выборе категорий

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#645]
В сообщении, где пользователь выбирает подкатегории из выбранной категории, в заголовке последнее предложение: "После этого, нажми на пункт "Готово" . Но кнопки "Готово" нет, а есть "Назад".

Нужно заменить в тексте сообщения название кнопки на "Назад" (со стрелочкой как в названии кнопки).

**Comment by Xalgina** [comment]
Во фразе _"После этого, нажми на пункт "Готово (Назад)"_ есть пунктуационная ошибка. "После этого" - это не вводная конструкция, она не должна выделяться запятой. Т.е. правильно _"После этого нажми на пункт "Готово (Назад)"_

По существу задачи - все ОК - текст с "Назад" там, где кнопка "Назад"
