### ISSUE TITLE
Баг: при включении подписки на задания  не удаляется запись в unsubscribe_reason

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#661]
После того, как волонтер нажимает кнопку "Отписаться от заданий" и указывает причину, в таблице unsubscribe_reason создается запись с причиной отписки.
Если волонтер включает подписку обратно, то запись из таблицы unsubscribe_reason не удаляется.
При этом если пользователь отписывается несколько раз, причина заменяется на новую (строчка для пользователя одна). Корректно будет удалять запись о причине отписке, если волонтер включил её обратно.

**Comment by StriderDunedain** [comment]
Немного запутался, где включается подписка. Вижу только все, связанное с Unsubscribe'ами. А где подписки снова включаются?

**Comment by gorskyolga** [comment]
@StriderDunedain , подписка включается и выключается кнопкой "Отписаться на заданий" / "Подписаться на задания" (в меню отображается кнопка в зависимости от того, включена ли подписка).
За обработку кнопок отвечает set_mailing в `src\bot\handlers\menu.py`.
