### ISSUE TITLE
Поменять url в вэб-аппах по заданиям

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#677]
У сообщений с заданиями есть кнопка "Посмотреть задание", открывающая вэб-апп.
Вэб-апп по заданию создается в get_task_web_app_info в `src\bot\web_apps.py`.
Сейчас для отображения вэб-аппа используется шаблон в settings.task_info_page_template_url и остальные файлы в папке `templates\task_info_page`.

Нужно поменять url и query-параметры таким образом, чтобы открывались ссылки вида "http://test6.procharity.corptest.ru/webapp/?task_id=135527", где task_id - это id задания (task.id).
Доменное имя выбирается при помощи PROCHARITY_URL.

Также нужно удалить папку `templates\task_info_page`.

**Comment by StriderDunedain** [comment]
Привет! Вопрос по url: 
> Доменное имя выбирается при помощи PROCHARITY_URL

Получается, надо поставить PROCHARITY_URL = "http://test6.procharity.corptest.ru/"?

**Comment by gorskyolga** [comment]
Нужно в task_info_page_template_url формировать url не как self.static_url с добавкой, а как self.PROCHARITY_URL с добавкой.

Значение PROCHARITY_URL в env.example указано "http://test6.procharity.corptest.ru/". Чтобы локальный бот открывал в вэб-аппе ссылки на тестовый сайт, нужно в `.env` указать это значение.
