### ISSUE TITLE
Копировать данные в external_site_user при их изменении в боте

### ISSUE THREAD

**Issue by gorskyolga** [Studio-Yandex-Practicum/ProCharity_back_2.0#683]
Часть данных о пользователе сайта, получаемых по эндпоинтам [ExternalSiteUser](http://127.0.0.1:8000/docs#/ExternalSiteUser) от сайта, можно изменить через бот. При этом эти данные обновляются в таблице user и users_categories, но не обновляются в таблице external_site_users.
Если пользователь поменяет такие данные через бот, а затем привяжется с другой учетки телеграм к тому же external_site_user, то у него снова будут старые настройки.

Нужно добавить обновление данных в таблице external_site_users при их изменении через бот:
1. для категорий, выбранных пользователем:
- при изменении через бот они сохраняются в таблице users_categories,
- нужно также обновлять их в таблице external_site_users поле specializations,
2. для настройки подписки на новые заданий:
- при изменении через бот сохраняется в таблице users поле has_mailing,
- нужно также обновлять их в таблице external_site_users поле has_mailing_new_tasks.

Правильно будет обновлять данные только, если они были успешно переданы на сайт. Для этого нужно добавить возврат True / False для методов procharity_api в `src\core\services\procharity_api.py` и использовать их:
- в `src\bot\handlers\categories.py` для procharity_api.send_user_bot_status;
- в `src\bot\handlers\menu.py` для procharity_api.send_user_categories.

**Comment by eugemos** [comment]
Однако, тут есть проблема из-за того, что API сайта сейчас не работает в части приема от бота уведомлений об изменении данных пользователя. Поэтому, если обусловить запись изменённых данных в `external_site_users` успешной отправкой уведомления на сайт, то она никогда не будет происходить и протестировать ничего не удастся.
Может, ввести настройку, которая бы отменяла это требование?

**Comment by gorskyolga** [comment]
[Вот этот PR](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/685) исправляет вызов эндпоинтов сайта, так что данные передаются успешно.
Токен для тестирования я пришлю в личку.

**Comment by gorskyolga** [comment]
Я запоздало поняла, что лучше всё-таки ввести настройку, про которую ты говорил, в таком виде:
- если токен указан в переменных окружения, то копировать данные при условии успешной отправки их на сайт;
- если токен не указан в переменных окружения или пустой, то копировать данные всегда.
У большинства разработчиков будет второй случай и правильнее, чтобы у них тоже данные между таблицами были согласованы.
